### ISSUE TITLE
코드 좋네연 이슈하나 투척하고 갑니다.

### ISSUE THREAD

**Issue by Pakrjihoon** [taxijjang/flat_form_crawling#1]
get_video_count_in_product 부분 

예외처리 항목에서 불필요한 print 문 삽입 보다 어디서 끊겼는지에 대한 중단점 체크해서 에러로그 뱉는거도 나쁘지않을 것 같고.

클린코드 적용을 위해선 불필요한 주석은 제거 하는게 좋을 것 같습니다.

**Comment by taxijjang** [comment]
오오 좋은 내용 감사합니다 참고하여 수정하도록 하겠습니다~
